import { Geist, Geist_Mono ,Orbitron,Rajdhani} from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
});

const rajdhani = Rajdhani({
  subsets: ["latin"],
  variable: "--font-rajdhani",
  weight: ["400","500","600","700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={orbitron.className} >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
